"""
PDF filler service — STUB.
Replace with real PDF generation (reportlab, PyPDF2, pdfrw, etc.) when ready.
"""

from models.session_state import SessionState


async def generate_pdf(session: SessionState) -> bytes:
    """
    STUB: Generate a simple text representation as a placeholder.

    TODO: Replace with actual PDF filling:
      1. Load blank FEMA PDF template
      2. Write each answer at the PDF coordinates from fema_template.py
      3. Return filled PDF bytes
    """
    lines = [
        "=" * 50,
        "  FEMA DISASTER AID FORM 009-0-3",
        "  (Generated by FormWhisper)",
        "=" * 50,
        "",
    ]

    for field_name, value in session.answers.items():
        label = field_name.replace("_", " ").title()
        lines.append(f"  {label}: {value}")

    lines.extend([
        "",
        "=" * 50,
        f"  Session ID: {session.session_id}",
        f"  Created: {session.created_at.isoformat()}",
        "=" * 50,
    ])

    content = "\n".join(lines)
    return content.encode("utf-8")
